USE [master]
GO

/****** Object:  Database [GMQA]    Script Date: 23/10/2015 22:33:41 ******/
DROP DATABASE [GMQA]
GO

/****** Object:  Database [GMQA]    Script Date: 23/10/2015 22:33:41 ******/
CREATE DATABASE [GMQA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GMQA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.GMQA\MSSQL\DATA\GMQA.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GMQA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.GMQA\MSSQL\DATA\GMQA_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GMQA] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GMQA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GMQA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GMQA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GMQA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GMQA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GMQA] SET ARITHABORT OFF 
GO

ALTER DATABASE [GMQA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GMQA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GMQA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GMQA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GMQA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GMQA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GMQA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GMQA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GMQA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GMQA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GMQA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GMQA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GMQA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GMQA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GMQA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GMQA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GMQA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GMQA] SET RECOVERY FULL 
GO

ALTER DATABASE [GMQA] SET  MULTI_USER 
GO

ALTER DATABASE [GMQA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GMQA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GMQA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GMQA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GMQA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GMQA] SET  READ_WRITE 
GO

